Repository OtakuMap/Otaku_SB, pull requests merged in 2025-02, with the labels that each got.

#88 Feat: 조회수 Top 7 리뷰 목록 조회 api
  src/main/java/com/otakumap/domain/reviews/controller/ReviewSearchController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryCustom.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
  src/main/java/com/otakumap/global/common/BaseEntity.java
Labels: ✨ Feature

#97 Feat: 특정 여행 후기 조회 API 구현
  src/main/java/com/otakumap/domain/event_review/converter/EventReviewConverter.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/image/converter/ImageConverter.java
  src/main/java/com/otakumap/domain/image/entity/Image.java
  src/main/java/com/otakumap/domain/place_review/converter/PlaceReviewConverter.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/enums/ReviewType.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/converter/RouteConverter.java
  src/main/java/com/otakumap/domain/route/dto/RouteResponseDTO.java
  src/main/java/com/otakumap/domain/route_item/converter/RouteItemConverter.java
  src/main/java/com/otakumap/domain/route_item/dto/RouteItemResponseDTO.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_item/repository/RouteItemRepository.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/ReviewHandler.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/RouteItemHandler.java
  src/main/java/com/otakumap/global/validation/annotation/ValidReviewId.java
  src/main/java/com/otakumap/global/validation/validator/ReviewIdValidator.java
Labels: ✨ Feature

#106 Feat: 메인 화면 배너 이미지 불러오기 api 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryCustom.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryImpl.java
  src/main/java/com/otakumap/domain/event/service/EventCustomService.java
  src/main/java/com/otakumap/domain/event/service/EventCustomServiceImpl.java
Labels: ✨ Feature

#109 Feat: 관련 키워드로 여행 후기 검색 결과 이미지 반환 구현
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
Labels: ✨ Feature

#116 Fix: 특정 여행 후기 조회 연관관계 수정
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route_item/converter/RouteItemConverter.java
  src/main/java/com/otakumap/domain/route_item/dto/RouteItemResponseDTO.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_item/enums/ItemType.java
  src/main/java/com/otakumap/domain/route_item/repository/RouteItemRepository.java
Labels: 🐞 BugFix

#118 Fix: 빌드 에러 수정
  src/main/java/com/otakumap/domain/place/entity/Place.java
Labels: 🐞 BugFix

#119 Feat: 커스텀 루트 저장 API 구현
  src/main/java/com/otakumap/domain/place/service/PlaceQueryService.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/converter/RouteConverter.java
  src/main/java/com/otakumap/domain/route_item/converter/RouteItemConverter.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeRequestDTO.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/global/validation/annotation/ExistPlace.java
  src/main/java/com/otakumap/global/validation/validator/PlaceExistValidator.java
Labels: ✨ Feature

#121 Feat: 저장된 루트 수정 API 구현
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route/service/RouteQueryService.java
  src/main/java/com/otakumap/domain/route/service/RouteQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeRequestDTO.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeResponseDTO.java
  src/main/java/com/otakumap/domain/route_like/entity/RouteLike.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/global/validation/annotation/ExistRoute.java
  src/main/java/com/otakumap/global/validation/validator/RouteExistValidator.java
Labels: ✨ Feature

#107 Feat: 특정 명소 관련 애니메이션 조회 API 구현
  src/main/java/com/otakumap/domain/place/DTO/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/controller/PlaceController.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryService.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/otakumap/domain/place_animation/repository/PlaceAnimationRepository.java
Labels: ✨ Feature

#124 Feat: 저장된 루트 목록 조회 API 구현 (+즐겨찾기 목록)
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeResponseDTO.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeQueryService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeQueryServiceImpl.java
Labels: ✨ Feature

#126 Feat: 즐겨찾기 여부까지 추가해서 저장된 장소 조회 API 구현
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/place_like/entity/PlaceLike.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryServiceImpl.java
  src/main/java/com/otakumap/global/config/CorsConfig.java
Labels: ✨ Feature

#127 Fix: setAllowedOriginPatterns() 활용하여 CORS 에러 해결
  src/main/java/com/otakumap/global/config/CorsConfig.java
Labels: 🐞 BugFix

#130 Feat: 루트 내 특정 장소 상세 정보 조회 API 구현
  src/main/java/com/otakumap/domain/place/DTO/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryService.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/route/controller/RouteController.java
  src/main/java/com/otakumap/domain/route_item/repository/RouteItemRepository.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeResponseDTO.java
Labels: ✨ Feature

#110 Feat: 이벤트/작품명 지도 검색 API 구현
  build.gradle
  src/main/java/com/otakumap/domain/animation/converter/AnimationConverter.java
  src/main/java/com/otakumap/domain/animation/dto/AnimationResponseDTO.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event_like/repository/EventLikeRepository.java
  src/main/java/com/otakumap/domain/event_location/converter/EventLocationConverter.java
  src/main/java/com/otakumap/domain/event_location/dto/EventLocationResponseDTO.java
  src/main/java/com/otakumap/domain/event_location/entity/EventLocation.java
  src/main/java/com/otakumap/domain/event_location/repository/EventLocationRepository.java
  src/main/java/com/otakumap/domain/mapping/repository/EventHashTagRepository.java
  src/main/java/com/otakumap/domain/place/DTO/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/controller/PlaceController.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/search/controller/SearchController.java
  src/main/java/com/otakumap/domain/search/converter/SearchConverter.java
  src/main/java/com/otakumap/domain/search/dto/SearchResponseDTO.java
  src/main/java/com/otakumap/domain/search/repository/SearchRepositoryCustom.java
  src/main/java/com/otakumap/domain/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/otakumap/domain/search/service/SearchService.java
  src/main/java/com/otakumap/domain/search/service/SearchServiceImpl.java
Labels: ✨ Feature

#129 Feat: 카테고리별 이벤트 검색 API 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryCustom.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryImpl.java
  src/main/java/com/otakumap/domain/event/service/EventCustomService.java
  src/main/java/com/otakumap/domain/event/service/EventCustomServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#134 Feat: 명소 한줄 후기에 대한 좋아요/싫어요 API 구현
  src/main/java/com/otakumap/domain/place_short_review/entity/PlaceShortReview.java
  src/main/java/com/otakumap/domain/user_reaction/DTO/UserReactionRequestDTO.java
  src/main/java/com/otakumap/domain/user_reaction/DTO/UserReactionResponseDTO.java
  src/main/java/com/otakumap/domain/user_reaction/controller/UserReactionController.java
  src/main/java/com/otakumap/domain/user_reaction/converter/UserReactionConverter.java
  src/main/java/com/otakumap/domain/user_reaction/entity/UserReaction.java
  src/main/java/com/otakumap/domain/user_reaction/repository/UserReactionRepository.java
  src/main/java/com/otakumap/domain/user_reaction/service/UserReactionCommandService.java
  src/main/java/com/otakumap/domain/user_reaction/service/UserReactionCommandServiceImpl.java
Labels: ✨ Feature

#137 Revert "Feat: 후기 작성 API 구현"
  src/main/java/com/otakumap/domain/animation/controller/AnimationController.java
  src/main/java/com/otakumap/domain/animation/converter/AnimationConverter.java
  src/main/java/com/otakumap/domain/animation/dto/AnimationRequestDTO.java
  src/main/java/com/otakumap/domain/animation/dto/AnimationResponseDTO.java
  src/main/java/com/otakumap/domain/animation/entity/Animation.java
  src/main/java/com/otakumap/domain/animation/repository/AnimationRepository.java
  src/main/java/com/otakumap/domain/animation/service/AnimationCommandService.java
  src/main/java/com/otakumap/domain/animation/service/AnimationCommandServiceImpl.java
  src/main/java/com/otakumap/domain/animation/service/AnimationQueryService.java
  src/main/java/com/otakumap/domain/animation/service/AnimationQueryServiceImpl.java
  src/main/java/com/otakumap/domain/event_animation/repository/EventAnimationRepository.java
  src/main/java/com/otakumap/domain/event_location/repository/EventLocationRepository.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/event_review_place/repository/EventReviewPlaceRepository.java
  src/main/java/com/otakumap/domain/image/entity/Image.java
  src/main/java/com/otakumap/domain/image/service/ImageCommandService.java
  src/main/java/com/otakumap/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/otakumap/domain/mapping/EventReviewPlace.java
  src/main/java/com/otakumap/domain/mapping/PlaceReviewPlace.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place_animation/repository/PlaceAnimationRepository.java
  src/main/java/com/otakumap/domain/place_review/controller/PlaceReviewController.java
  src/main/java/com/otakumap/domain/place_review/converter/PlaceReviewConverter.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewRequestDTO.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandService.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_review_place/repository/PlaceReviewPlaceRepository.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewRequestDTO.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/route/converter/RouteConverter.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_item/repository/RouteItemRepository.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/AnimationHandler.java
Labels: 🐞 BugFix

#141 Feat: 저장한 루트가 새로 생성되지 않고 기존 것을 반환하도록 변경
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
Labels: ✨ Feature

#144 Feat: HTTPS 적용
  src/main/java/com/otakumap/global/config/CorsConfig.java
  src/main/java/com/otakumap/global/config/WebConfig.java
Labels: ✨ Feature

#145 Fix: CORS 에러 해결을 위해 WebConfig에 배포된 프론트엔드 URL 추가
  src/main/java/com/otakumap/global/config/WebConfig.java
Labels: 🐞 BugFix

#139 Feat: 이벤트/장소 검색 비회원 요청 허용
  src/main/java/com/otakumap/domain/animation/converter/AnimationConverter.java
  src/main/java/com/otakumap/domain/animation/dto/AnimationResponseDTO.java
  src/main/java/com/otakumap/domain/auth/jwt/annotation/CurrentUser.java
  src/main/java/com/otakumap/domain/auth/jwt/resolver/CurrentUserResolver.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event_like/repository/EventLikeRepository.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/search/controller/SearchController.java
  src/main/java/com/otakumap/domain/search/service/SearchService.java
  src/main/java/com/otakumap/domain/search/service/SearchServiceImpl.java
  src/main/java/com/otakumap/global/config/SecurityConfig.java
Labels: ✨ Feature

#148 Feat: 이벤트 상세 조회 API의 이벤트 관련 애니 이름 가져오는 로직 수정
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event/service/EventQueryServiceImpl.java
Labels: ✨ Feature

#152 Feat: 특정 장소의 전체 후기 조회 API 로직 수정
  src/main/java/com/otakumap/domain/place_review/converter/PlaceReviewConverter.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/place_review_place/repository/PlaceReviewPlaceRepository.java
  src/main/java/com/otakumap/domain/route_item/repository/RouteItemRepository.java
Labels: ✨ Feature

#154 Feat: QueryDSL 구문에서 PlaceReviewPlace를 사용하도록 수정
  src/main/java/com/otakumap/domain/place_review_place/repository/PlaceReviewPlaceRepository.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
Labels: ✨ Feature

#158 Fix: 저장된 장소 연관관계 수정
  src/main/java/com/otakumap/domain/place_like/entity/PlaceLike.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryServiceImpl.java
Labels: 🐞 BugFix

#159 Feat: 루트 내 특정 장소 상세 정보 조회 API 로직 수정
  src/main/java/com/otakumap/domain/hash_tag/converter/HashTagConverter.java
  src/main/java/com/otakumap/domain/place/DTO/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryService.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/controller/RouteController.java
Labels: ✨ Feature

#160 Fix: 랜덤 로직 변경
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryImpl.java
Labels: 🐞 BugFix

#165 Feat: 이벤트 한 줄 리뷰 수정, 삭제 API 구현
  src/main/java/com/otakumap/domain/event_short_review/controller/EventShortReviewController.java
  src/main/java/com/otakumap/domain/event_short_review/dto/EventShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/event_short_review/entity/EventShortReview.java
  src/main/java/com/otakumap/domain/event_short_review/service/EventShortReviewCommandService.java
  src/main/java/com/otakumap/domain/event_short_review/service/EventShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#163 Feat: 회원가입 시 프로필로 기본 이미지 설정
  src/main/java/com/otakumap/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/otakumap/domain/image/entity/Image.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#168 Feat: 명소 한 줄 리뷰 수정, 삭제 API 구현
  src/main/java/com/otakumap/domain/event_short_review/controller/EventShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/controller/PlaceShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/converter/PlaceShortReviewConverter.java
  src/main/java/com/otakumap/domain/place_short_review/dto/PlaceShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/place_short_review/dto/PlaceShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_short_review/entity/PlaceShortReview.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandService.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#171 Feat: 회원가입 시 닉네임 랜덤 생성
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
Labels: ✨ Feature

#161 Feat: 이메일 수정 API 구현
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#162 Feat: 알림 생성 구현
  src/main/java/com/otakumap/OtakumapApplication.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event/repository/EventRepository.java
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/notification/converter/NotificationConverter.java
  src/main/java/com/otakumap/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/otakumap/domain/notification/service/EventSchedulerService.java
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandService.java
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
Labels: ✨ Feature

#151 Feat: 루트 상세 정보 조회 api 수정
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/route/converter/RouteConverter.java
  src/main/java/com/otakumap/domain/route/dto/RouteResponseDTO.java
  src/main/java/com/otakumap/domain/route/service/RouteQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#169 Feat: 지도에서 장소 및 이벤트 정보 보기 api 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/repository/EventRepository.java
  src/main/java/com/otakumap/domain/map/controller/MapController.java
  src/main/java/com/otakumap/domain/map/converter/MapConverter.java
  src/main/java/com/otakumap/domain/map/dto/MapResponseDTO.java
  src/main/java/com/otakumap/domain/map/repository/MapRepositoryCustom.java
  src/main/java/com/otakumap/domain/map/repository/MapRepositoryCustomImpl.java
  src/main/java/com/otakumap/domain/map/service/MapCustomService.java
  src/main/java/com/otakumap/domain/map/service/MapCustomServiceImpl.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place_review_place/repository/PlaceReviewPlaceRepository.java
Labels: ✨ Feature

#177 Feat: 저장한 이벤트 삭제 API 수정
  src/main/java/com/otakumap/domain/event_like/controller/EventLikeController.java
  src/main/java/com/otakumap/domain/event_like/repository/EventLikeRepository.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandServiceImpl.java
Labels: ✨ Feature

#179 Feat: 카카오 로그인 시 이름 대신 닉네임으로 가져오도록 임시 변경
  src/main/java/com/otakumap/domain/auth/dto/KakaoUserInfo.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
Labels: ✨ Feature

#175 Refactor: 명소 한 줄 조회 api 데이터 수정
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_review/controller/EventReviewController.java
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandService.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_short_review/repository/EventShortReviewRepository.java
  src/main/java/com/otakumap/domain/place_short_review/controller/PlaceShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/converter/PlaceShortReviewConverter.java
  src/main/java/com/otakumap/domain/place_short_review/dto/PlaceShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_short_review/repository/PlaceShortReviewRepository.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandService.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/config/SecurityConfig.java
Labels: ♻️ Refactor

#181 Feat: 전체적으로 수정
  src/main/java/com/otakumap/domain/animation/entity/Animation.java
  src/main/java/com/otakumap/domain/animation/service/AnimationCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event_location/repository/EventLocationRepository.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/hash_tag/converter/HashTagConverter.java
  src/main/java/com/otakumap/domain/hash_tag/entity/HashTag.java
  src/main/java/com/otakumap/domain/hash_tag/repository/HashTagRepository.java
  src/main/java/com/otakumap/domain/map/controller/MapController.java
  src/main/java/com/otakumap/domain/map/repository/MapRepositoryCustomImpl.java
  src/main/java/com/otakumap/domain/map/service/MapCustomServiceImpl.java
  src/main/java/com/otakumap/domain/mapping/AnimationHashtag.java
  src/main/java/com/otakumap/domain/mapping/PlaceAnimation.java
  src/main/java/com/otakumap/domain/mapping/PlaceAnimationHashTag.java
  src/main/java/com/otakumap/domain/mapping/repository/AnimationHashTagRepository.java
  src/main/java/com/otakumap/domain/mapping/repository/EventHashTagRepository.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_review/controller/PlaceReviewController.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/route/converter/RouteConverter.java
  src/main/java/com/otakumap/domain/route/service/RouteQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route_item/converter/RouteItemConverter.java
  src/main/java/com/otakumap/domain/search/controller/SearchController.java
  src/main/java/com/otakumap/domain/search/service/SearchServiceImpl.java
Labels: ✨ Feature

#188 Feat: 해시태그 가져오는 로직 수정
  src/main/java/com/otakumap/domain/event_location/repository/EventLocationRepository.java
  src/main/java/com/otakumap/domain/place_review/controller/PlaceReviewController.java
  src/main/java/com/otakumap/domain/place_review/converter/PlaceReviewConverter.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/search/controller/SearchController.java
  src/main/java/com/otakumap/domain/search/service/SearchServiceImpl.java
Labels: ✨ Feature

#186 Feat: 진행 중인 이벤트 API에 사용자 좋아요 여부 데이터 추가
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryCustom.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryImpl.java
  src/main/java/com/otakumap/domain/event/service/EventCustomService.java
  src/main/java/com/otakumap/domain/event/service/EventCustomServiceImpl.java
Labels: ✨ Feature

#183 Feat: 결제 기능과 관련된 기본 설정 및 entity
  build.gradle
  src/main/java/com/otakumap/domain/payment/entity/Payment.java
  src/main/java/com/otakumap/domain/payment/enums/PaymentStatus.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
Labels: ✨ Feature

#194 Feat: 저장된 장소 상세 조회 API, 루트 내 특정 장소 상세 정보 조회 API 수정
  src/main/java/com/otakumap/domain/place/DTO/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/dto/PlaceLikeResponseDTO.java
Labels: ✨ Feature

#196 Feat: 저장한 장소 삭제 API 구현- 지도창에서 하트 누르기
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandServiceImpl.java
Labels: ✨ Feature

#193 Feat: 구매하기 기능 기본 entity & enum
  src/main/java/com/otakumap/domain/payment/entity/Payment.java
  src/main/java/com/otakumap/domain/payment/enums/PaymentStatus.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
Labels: ✨ Feature

#200 Feat: 소셜 로그인 시 프로필로 기본 이미지 설정
  src/main/java/com/otakumap/domain/auth/service/SocialAuthServiceImpl.java
Labels: ✨ Feature

#197 Feat: 이벤트 한줄리뷰 좋아요/싫어요 API 구현
  src/main/java/com/otakumap/domain/event_reaction/controller/EventReactionController.java
  src/main/java/com/otakumap/domain/event_reaction/converter/EventReactionConverter.java
  src/main/java/com/otakumap/domain/event_reaction/dto/EventReactionRequestDTO.java
  src/main/java/com/otakumap/domain/event_reaction/dto/EventReactionResponseDTO.java
  src/main/java/com/otakumap/domain/event_reaction/entity/EventReaction.java
  src/main/java/com/otakumap/domain/event_reaction/repository/EventReactionRepository.java
  src/main/java/com/otakumap/domain/event_reaction/service/EventReactionCommandService.java
  src/main/java/com/otakumap/domain/event_reaction/service/EventReactionCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_short_review/entity/EventShortReview.java
Labels: ✨ Feature

#199 Feat: 구매하기 기능 entity 및 enum
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/transaction/entity/Transaction.java
  src/main/java/com/otakumap/domain/transaction/enums/TransactionType.java
Labels: ✨ Feature

#202 Feat: 결제 검증 api 구현
  build.gradle
  src/main/java/com/otakumap/domain/payment/controller/PaymentController.java
  src/main/java/com/otakumap/domain/payment/dto/PaymentVerifyRequest.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandService.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandServiceImpl.java
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/transaction/entity/Transaction.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/PaymentHandler.java
  src/main/java/com/otakumap/global/config/IamportConfig.java
Labels: ✨ Feature

#203 Feat: 포인트 충전 내역 확인 API 구현
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/dto/PointResponseDTO.java
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/point/service/PointQueryservice.java
  src/main/java/com/otakumap/domain/point/service/PointQueryserviceImpl.java
Labels: ✨ Feature

#198 Refactor: 지도에서 장소 및 이벤트 정보 보기 API 해시태그 관련 로직 수정 및 애니메이션 관련 데이터 추가
  src/main/java/com/otakumap/domain/map/controller/MapController.java
  src/main/java/com/otakumap/domain/map/converter/MapConverter.java
  src/main/java/com/otakumap/domain/map/dto/MapResponseDTO.java
  src/main/java/com/otakumap/domain/map/repository/MapRepositoryCustomImpl.java
  src/main/java/com/otakumap/domain/map/service/MapCustomServiceImpl.java
Labels: ♻️ Refactor

#204 Feat: 구매/수익 내역 조회 API
  src/main/java/com/otakumap/domain/transaction/controller/TransactionController.java
  src/main/java/com/otakumap/domain/transaction/converter/TransactionConverter.java
  src/main/java/com/otakumap/domain/transaction/dto/TransactionResponseDTO.java
  src/main/java/com/otakumap/domain/transaction/entity/Transaction.java
  src/main/java/com/otakumap/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/otakumap/domain/transaction/service/TransactionQueryService.java
  src/main/java/com/otakumap/domain/transaction/service/TransactionQueryServiceImpl.java
Labels: ✨ Feature

#205 Feat: 포인트 잔액 조회 API
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/dto/PointResponseDTO.java
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/point/service/PointQueryservice.java
  src/main/java/com/otakumap/domain/point/service/PointQueryserviceImpl.java
Labels: ✨ Feature

#210 Feat: 카테고리 페이지에서 이벤트를 이벤트명/작품명으로 검색 API 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/service/EventQueryService.java
  src/main/java/com/otakumap/domain/event/service/EventQueryServiceImpl.java
  src/main/java/com/otakumap/domain/search/repository/SearchRepositoryCustom.java
  src/main/java/com/otakumap/domain/search/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#211 Feat: 후기 구매 API 구현
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryCustom.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/transaction/entity/Transaction.java
  src/main/java/com/otakumap/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/TransactionHandler.java
Labels: ✨ Feature

#213 Fix: 한줄 리뷰 삭제 시 외래키 제약 조건 오류 해결
  src/main/java/com/otakumap/domain/event_reaction/controller/EventReactionController.java
  src/main/java/com/otakumap/domain/event_reaction/converter/EventReactionConverter.java
  src/main/java/com/otakumap/domain/event_reaction/repository/EventReactionRepository.java
  src/main/java/com/otakumap/domain/event_reaction/service/EventReactionCommandService.java
  src/main/java/com/otakumap/domain/event_short_review/entity/EventShortReview.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/controller/EventShortReviewReactionController.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/converter/EventShortReviewReactionConverter.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/dto/EventShortReviewReactionRequestDTO.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/dto/EventShortReviewReactionResponseDTO.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/entity/EventShortReviewReaction.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/repository/EventShortReviewReactionRepository.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/service/EventShortReviewReactionCommandService.java
  src/main/java/com/otakumap/domain/event_short_review_reaction/service/EventShortReviewReactionCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_short_review/entity/PlaceShortReview.java
Labels: 🐞 BugFix

#216 Feat: 비밀번호 변경 API 구현
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ Feature

#209 Feat: 결제 검증 api
  src/main/java/com/otakumap/domain/payment/controller/PaymentController.java
  src/main/java/com/otakumap/domain/payment/dto/PaymentVerifyRequest.java
  src/main/java/com/otakumap/domain/payment/entity/UserPayment.java
  src/main/java/com/otakumap/domain/payment/repository/PaymentRepository.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryServiceImpl.java
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/dto/PointRequestDTO.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/point/service/PointCommandService.java
  src/main/java/com/otakumap/domain/point/service/PointCommandServiceImpl.java
Labels: ✨ Feature

#218 Feat: 유저 개인정보 조회 API 호출 시 후기 후원금 내역 조회 가능하게 변경
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
Labels: ✨ Feature

#222 Fix: 결제 검증 & 포인트 충전 api
  src/main/java/com/otakumap/domain/order/dto/OrderDto.java
  src/main/java/com/otakumap/domain/order/entity/Order.java
  src/main/java/com/otakumap/domain/order/repository/OrderRepository.java
  src/main/java/com/otakumap/domain/payment/controller/PaymentController.java
  src/main/java/com/otakumap/domain/payment/dto/PaymentVerifyRequest.java
  src/main/java/com/otakumap/domain/payment/entity/UserPayment.java
  src/main/java/com/otakumap/domain/payment/repository/PaymentRepository.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandService.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandServiceImpl.java
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/point/service/PointCommandService.java
  src/main/java/com/otakumap/domain/point/service/PointCommandServiceImpl.java
  src/main/java/com/otakumap/domain/transaction/dto/TransactionResponseDTO.java
  src/main/java/com/otakumap/domain/transaction/entity/Transaction.java
Labels: 🐞 BugFix, ✨ Feature

#220 Refactor: 마이페이지 후기 관련 API 수정
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandService.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/dto/UserResponseDTO.java
  src/main/java/com/otakumap/domain/user/service/UserQueryService.java
  src/main/java/com/otakumap/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ♻️ Refactor

#223 Feat: 후기 작성 시 열람범위 설정
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandService.java
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewRequestDTO.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
Labels: ✨ Feature

#227 Refactor: 구매 로직 변동에 따른 현재 포인트 반환 API 로직 변경
  src/main/java/com/otakumap/domain/point/repository/PointRepository.java
  src/main/java/com/otakumap/domain/point/service/PointQueryserviceImpl.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
Labels: ♻️ Refactor

#228 Feat: 입력받은 placeId로 변경되도록 수정
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
Labels: ✨ Feature

#226 Fix: 알림 설정 변경 API가 정상 작동하지 않는 문제 수정
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
Labels: 🐞 BugFix

#224 Feat: 리뷰와 루트 1:N 관계로 수정
  src/main/java/com/otakumap/domain/event_review/converter/EventReviewConverter.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route_like/dto/RouteLikeRequestDTO.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature, ♻️ Refactor

#232 Feat: 구매 여부 조회 API 구현
  src/main/java/com/otakumap/domain/reviews/controller/ReviewController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryCustom.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
Labels: ✨ Feature

#233 Feat: 포인트 충전 api 수정
  src/main/java/com/otakumap/domain/order/dto/OrderDto.java
  src/main/java/com/otakumap/domain/order/entity/Order.java
  src/main/java/com/otakumap/domain/order/repository/OrderRepository.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandService.java
  src/main/java/com/otakumap/domain/payment/service/PaymentCommandServiceImpl.java
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/dto/PointResponseDTO.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/user/entity/User.java
Labels: ✨ Feature, ♻️ Refactor

#234 Refactor: Entity 변경에 맞춰 후기 구매 api 수정
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
Labels: ♻️ Refactor

#235 Refactor: 포인트 충전 내역을 user의 totalPoint 칼럼값 반환하게 수정
  src/main/java/com/otakumap/domain/point/service/PointQueryserviceImpl.java
Labels: ♻️ Refactor

#236 Refactor: 안 쓰는 파일 및 코드 삭제
  src/main/java/com/otakumap/domain/order/dto/OrderDto.java
  src/main/java/com/otakumap/domain/order/entity/Order.java
  src/main/java/com/otakumap/domain/order/repository/OrderRepository.java
  src/main/java/com/otakumap/domain/point/controller/PointController.java
  src/main/java/com/otakumap/domain/point/converter/PointConverter.java
  src/main/java/com/otakumap/domain/point/entity/Point.java
  src/main/java/com/otakumap/domain/point/service/PointCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
Labels: ♻️ Refactor

#238 Feat: 후기 상세 조회 User nickname 반환으로 수정
  src/main/java/com/otakumap/domain/order/dto/OrderDto.java
  src/main/java/com/otakumap/domain/order/entity/Order.java
  src/main/java/com/otakumap/domain/order/repository/OrderRepository.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
Labels: ✨ Feature
