Repository OtakuMap/Otaku_SB, pull requests merged in 2025-01, with the labels that each got.

#3 Feat: 저장한 이벤트 관련 API 구현
  build.gradle
  src/main/java/com/otakumap/OtakumapApplication.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event/entity/enums/EventStatus.java
  src/main/java/com/otakumap/domain/event/entity/enums/EventType.java
  src/main/java/com/otakumap/domain/event/entity/enums/Genre.java
  src/main/java/com/otakumap/domain/event/repository/EventRepository.java
  src/main/java/com/otakumap/domain/event_like/controller/EventLikeController.java
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/event_like/dto/EventLikeResponseDTO.java
  src/main/java/com/otakumap/domain/event_like/entity/EventLike.java
  src/main/java/com/otakumap/domain/event_like/repository/EventLikeRepository.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryServiceImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/entity/enums/Role.java
  src/main/java/com/otakumap/domain/user/entity/enums/SocialType.java
  src/main/java/com/otakumap/domain/user/entity/enums/UserStatus.java
  src/main/java/com/otakumap/domain/user/repository/UserRepository.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/EventHandler.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/UserHandler.java
  src/main/java/com/otakumap/global/validation/annotation/ExistEventLike.java
  src/main/java/com/otakumap/global/validation/validator/EventLikeExistValidator.java
Labels: ✨ Feature

#8 [Feat] 이벤트 상세 설명, 한 줄 후기 작성 API 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event/entity/enums/EventStatus.java
  src/main/java/com/otakumap/domain/event/entity/enums/EventType.java
  src/main/java/com/otakumap/domain/event/service/EventQueryService.java
  src/main/java/com/otakumap/domain/event/service/EventQueryServiceImpl.java
  src/main/java/com/otakumap/domain/eventLocation/converter/EventLocationConverter.java
  src/main/java/com/otakumap/domain/eventLocation/dto/EventLocationResponseDTO.java
  src/main/java/com/otakumap/domain/eventLocation/entity/EventLocation.java
  src/main/java/com/otakumap/domain/eventShortReview/controller/EventShortReviewController.java
  src/main/java/com/otakumap/domain/eventShortReview/converter/EventShortReviewConverter.java
  src/main/java/com/otakumap/domain/eventShortReview/dto/EventShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/eventShortReview/dto/EventShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/eventShortReview/entity/EventShortReview.java
  src/main/java/com/otakumap/domain/eventShortReview/repository/EventShortReviewRepository.java
  src/main/java/com/otakumap/domain/eventShortReview/service/EventShortReviewCommandService.java
  src/main/java/com/otakumap/domain/eventShortReview/service/EventShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/image/converter/ImageConverter.java
  src/main/java/com/otakumap/domain/image/dto/ImageResponseDTO.java
  src/main/java/com/otakumap/domain/image/entity/Image.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/enums/Role.java
  src/main/java/com/otakumap/domain/user/enums/SocialType.java
  src/main/java/com/otakumap/domain/user/enums/UserStatus.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/EventHandler.java
Labels: ✨ Feature

#10 Feat: 명소 한 줄 후기 불러오기(R) API 구현
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place_short_review/DTO/PlaceShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_short_review/controller/PlaceShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/converter/PlaceShortReviewConverter.java
  src/main/java/com/otakumap/domain/place_short_review/entity/PlaceShortReview.java
  src/main/java/com/otakumap/domain/place_short_review/repository/PlaceShortReviewRepository.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewQueryService.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/validation/annotation/ExistPlace.java
  src/main/java/com/otakumap/global/validation/validator/PlaceExistValidator.java
Labels: ✨ Feature

#12 Feat: 명소 한 줄 후기 작성 API 구현
  src/main/java/com/otakumap/domain/place_short_review/DTO/PlaceShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/place_short_review/DTO/PlaceShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_short_review/controller/PlaceShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/converter/PlaceShortReviewConverter.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandService.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/PlaceHandler.java
Labels: ✨ Feature

#15 Feat: 이벤트 한 줄 리뷰 조회 API 구현
  src/main/java/com/otakumap/domain/eventShortReview/controller/EventShortReviewController.java
  src/main/java/com/otakumap/domain/eventShortReview/converter/EventShortReviewConverter.java
  src/main/java/com/otakumap/domain/eventShortReview/dto/EventShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/eventShortReview/repository/EventShortReviewRepository.java
  src/main/java/com/otakumap/domain/eventShortReview/service/EventShortReviewCommandService.java
  src/main/java/com/otakumap/domain/eventShortReview/service/EventShortReviewCommandServiceImpl.java
Labels: ✨ Feature

#16 Feat: 후기 작성 API 구현
  src/main/java/com/otakumap/domain/place_review/controller/PlaceReviewController.java
  src/main/java/com/otakumap/domain/place_review/converter/PlaceReviewConverter.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewRequestDTO.java
  src/main/java/com/otakumap/domain/place_review/dto/PlaceReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandService.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandServiceImpl.java
Labels: ✨ Feature

#22 Feat: 일반 로그인 API 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/otakumap/OtakumapApplication.java
  src/main/java/com/otakumap/domain/auth/controller/AuthController.java
  src/main/java/com/otakumap/domain/auth/dto/AuthRequestDTO.java
  src/main/java/com/otakumap/domain/auth/dto/AuthResponseDTO.java
  src/main/java/com/otakumap/domain/auth/jwt/annotation/CurrentUser.java
  src/main/java/com/otakumap/domain/auth/jwt/dto/JwtDTO.java
  src/main/java/com/otakumap/domain/auth/jwt/filter/JwtFilter.java
  src/main/java/com/otakumap/domain/auth/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/otakumap/domain/auth/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/otakumap/domain/auth/jwt/resolver/CurrentUserResolver.java
  src/main/java/com/otakumap/domain/auth/jwt/userdetails/PrincipalDetails.java
  src/main/java/com/otakumap/domain/auth/jwt/userdetails/PrincipalDetailsService.java
  src/main/java/com/otakumap/domain/auth/jwt/util/JwtProvider.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandService.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/otakumap/domain/auth/service/MailService.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/repository/UserRepository.java
  src/main/java/com/otakumap/domain/user/service/UserQueryService.java
  src/main/java/com/otakumap/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/AuthHandler.java
  src/main/java/com/otakumap/global/config/AsyncConfig.java
  src/main/java/com/otakumap/global/config/MailConfig.java
  src/main/java/com/otakumap/global/config/RedisConfig.java
  src/main/java/com/otakumap/global/config/SecurityConfig.java
  src/main/java/com/otakumap/global/config/WebConfig.java
  src/main/java/com/otakumap/global/util/RedisUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#24 Feat: 이벤트 후기(게시글) 조회 API 구현
  src/main/java/com/otakumap/domain/event_review/controller/EventReviewController.java
  src/main/java/com/otakumap/domain/event_review/converter/EventReviewConverter.java
  src/main/java/com/otakumap/domain/event_review/dto/EventReviewResponseDTO.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/event_review/repository/EventReviewRepository.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandServivce.java
  src/main/java/com/otakumap/domain/event_review/service/EventReviewCommandServivceImpl.java
Labels: ✨ Feature

#30 Feat: 소셜 로그인 API 구현
  build.gradle
  src/main/java/com/otakumap/domain/auth/controller/AuthController.java
  src/main/java/com/otakumap/domain/auth/dto/AuthRequestDTO.java
  src/main/java/com/otakumap/domain/auth/dto/GoogleUserInfo.java
  src/main/java/com/otakumap/domain/auth/dto/KakaoUserInfo.java
  src/main/java/com/otakumap/domain/auth/dto/NaverUserInfo.java
  src/main/java/com/otakumap/domain/auth/service/SocialAuthService.java
  src/main/java/com/otakumap/domain/auth/service/SocialAuthServiceImpl.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/config/SocialProperties.java
  src/main/java/com/otakumap/global/config/WebConfig.java
  src/main/java/com/otakumap/global/util/UuidGenerator.java
  src/main/resources/application.yml
Labels: ✨ Feature

#34 Feat: 키워드로 여행 후기 검색 API 구현
  build.gradle
  src/main/java/com/otakumap/domain/animation/entity/Animation.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/mapping/EventAnimation.java
  src/main/java/com/otakumap/domain/mapping/PlaceAnimation.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewSearchController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryCustom.java
  src/main/java/com/otakumap/domain/reviews/repository/ReviewRepositoryImpl.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryService.java
  src/main/java/com/otakumap/domain/reviews/service/ReviewQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/SearchHandler.java
  src/main/java/com/otakumap/global/config/QueryDSLConfig.java
Labels: ✨ Feature

#33 Feat: 회원 정보 조회 API 구현
  src/main/java/com/otakumap/domain/notification/entity/Notification.java
  src/main/java/com/otakumap/domain/notification/repository/NotificationRepository.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/dto/UserResponseDTO.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserQueryService.java
  src/main/java/com/otakumap/domain/user/service/UserQueryServiceImpl.java
Labels: ✨ Feature

#39 Feat: 이벤트 제보하기 API 구현
  src/main/java/com/otakumap/domain/notification/entity/Notification.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/util/EmailUtil.java
Labels: ✨ Feature

#41 Feat: 저장한 장소 조회 및 삭제 테스트 코드 작성
  src/test/java/com/otakumap/place_like/PlaceLikeControllerTest.java
Labels: 🧪Test

#47 Feat: 명소 저장하기 API 구현
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
Labels: ✨ Feature

#43 Feat: 저장된 장소 조회 API 구현
  src/main/java/com/otakumap/domain/place/controller/PlaceController.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place/service/PlaceService.java
Labels: ✨ Feature

#53 Feat: 칼럼명 description -> detail로 변경 (erd 문서에 맞춰서)
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
Labels: ✨ Feature

#54 [CI] CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
Labels: 🌏 CI/CD

#51 Feat: 알림 설정 수정 API 구현
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#55 [CI] deploy.yml 수정
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🌏 CI/CD

#58 Feat: 저장한 장소 조회 API 수정
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/dto/PlaceLikeResponseDTO.java
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryServiceImpl.java
Labels: ✨ Feature

#56 Feat: 내가 작성한 후기 조회 API 구현
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/dto/UserResponseDTO.java
  src/main/java/com/otakumap/domain/user/service/UserQueryService.java
  src/main/java/com/otakumap/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/otakumap/global/validation/annotation/CheckPage.java
  src/main/java/com/otakumap/global/validation/validator/CheckPageValidator.java
Labels: ✨ Feature

#64 Feat: 중복된 API 삭제 작업
  src/main/java/com/otakumap/domain/place/controller/PlaceController.java
  src/main/java/com/otakumap/domain/place/converter/PlaceConverter.java
  src/main/java/com/otakumap/domain/place/dto/PlaceResponseDTO.java
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place/repository/PlaceRepository.java
  src/main/java/com/otakumap/domain/place/service/PlaceService.java
Labels: ✨ Feature

#49 Feat: 루트 저장 API 구현
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route/repository/RouteRepository.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_item/enums/ItemType.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/entity/RouteLike.java
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/RouteHandler.java
Labels: ✨ Feature

#71 Fix: Revert "Feat: 루트 저장 API 구현"
  src/main/java/com/otakumap/domain/event_review/entity/EventReview.java
  src/main/java/com/otakumap/domain/place_review/entity/PlaceReview.java
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route/repository/RouteRepository.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_item/enums/ItemType.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/entity/RouteLike.java
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/RouteHandler.java
Labels: 🐞 BugFix

#72 Feat: 루트 저장 API 구현
  .gitignore
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route/enums/ItemType.java
  src/main/java/com/otakumap/domain/route/repository/RouteRepository.java
  src/main/java/com/otakumap/domain/route_item/entity/RouteItem.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/entity/RouteLike.java
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/RouteHandler.java
Labels: ✨ Feature

#61 Feat: 이벤트 저장하기(찜하기) 기능 구현
  src/main/java/com/otakumap/domain/event_like/controller/EventLikeController.java
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/reviews/controller/ReviewSearchController.java
  src/main/java/com/otakumap/domain/reviews/converter/ReviewConverter.java
  src/main/java/com/otakumap/domain/reviews/dto/ReviewResponseDTO.java
Labels: ✨ Feature

#73 Feat: 아이디 찾기, 비밀번호 찾기, 비밀번호 변경 API 구현
  src/main/java/com/otakumap/domain/auth/controller/AuthController.java
  src/main/java/com/otakumap/domain/auth/dto/AuthRequestDTO.java
  src/main/java/com/otakumap/domain/auth/dto/AuthResponseDTO.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandService.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/otakumap/domain/auth/service/AuthQueryService.java
  src/main/java/com/otakumap/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/com/otakumap/domain/auth/service/MailService.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/dto/UserRequestDTO.java
  src/main/java/com/otakumap/domain/user/repository/UserRepository.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/config/SecurityConfig.java
Labels: ✨ Feature

#74 Feat: 회원가입 로직 수정
  src/main/java/com/otakumap/domain/auth/controller/AuthController.java
  src/main/java/com/otakumap/domain/auth/dto/AuthRequestDTO.java
  src/main/java/com/otakumap/domain/auth/dto/AuthResponseDTO.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandService.java
  src/main/java/com/otakumap/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/otakumap/domain/auth/service/AuthQueryService.java
  src/main/java/com/otakumap/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/com/otakumap/domain/user/converter/UserConverter.java
  src/main/java/com/otakumap/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#77 Feat: 알림 목록 조회/읽음처리 API 구현
  src/main/java/com/otakumap/domain/notification/controller/NotificationController.java
  src/main/java/com/otakumap/domain/notification/converter/NotificationConverter.java
  src/main/java/com/otakumap/domain/notification/dto/NotificationResponseDTO.java
  src/main/java/com/otakumap/domain/notification/entity/Notification.java
  src/main/java/com/otakumap/domain/notification/entity/enums/NotificationType.java
  src/main/java/com/otakumap/domain/notification/repository/NotificationRepository.java
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandService.java
  src/main/java/com/otakumap/domain/notification/service/NotificationCommandServiceImpl.java
  src/main/java/com/otakumap/domain/notification/service/NotificationQueryService.java
  src/main/java/com/otakumap/domain/notification/service/NotificationQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/NotificationHandler.java
Labels: ✨ Feature

#79 Feat: 저장한 루트 삭제 API 구현
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeQueryService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeQueryServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/validation/annotation/ExistRouteLike.java
  src/main/java/com/otakumap/global/validation/validator/RouteLikeExistValidator.java
Labels: ✨ Feature

#76 Refactor: 저장한 이벤트에 @CurrentUser 어노테이션 적용
  src/main/java/com/otakumap/domain/event_like/controller/EventLikeController.java
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryServiceImpl.java
Labels: ♻️ Refactor

#80 Feat: 모든 리뷰 삭제 API 구현
  src/main/java/com/otakumap/domain/place_review/repository/PlaceReviewRepository.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandService.java
  src/main/java/com/otakumap/domain/place_review/service/PlaceReviewCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
Labels: ✨ Feature

#84 Fix: CORS 에러 수정
  src/main/java/com/otakumap/global/config/CorsConfig.java
  src/main/java/com/otakumap/global/config/SecurityConfig.java
  src/main/java/com/otakumap/global/config/WebConfig.java
Labels: 🐞 BugFix

#85 Feat: 명소 한줄 후기 작성 API 구현
  src/main/java/com/otakumap/domain/place_animation/repository/PlaceAnimationRepository.java
  src/main/java/com/otakumap/domain/place_short_review/DTO/PlaceShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/place_short_review/DTO/PlaceShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/place_short_review/controller/PlaceShortReviewController.java
  src/main/java/com/otakumap/domain/place_short_review/converter/PlaceShortReviewConverter.java
  src/main/java/com/otakumap/domain/place_short_review/entity/PlaceShortReview.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandService.java
  src/main/java/com/otakumap/domain/place_short_review/service/PlaceShortReviewCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#82 Feat: 저장한 이벤트 즐겨찾기/즐겨찾기 취소, 저장한 이벤트 즐겨찾기 목록 조회 API 구현
  src/main/java/com/otakumap/domain/event_like/controller/EventLikeController.java
  src/main/java/com/otakumap/domain/event_like/converter/EventLikeConverter.java
  src/main/java/com/otakumap/domain/event_like/dto/EventLikeRequestDTO.java
  src/main/java/com/otakumap/domain/event_like/dto/EventLikeResponseDTO.java
  src/main/java/com/otakumap/domain/event_like/entity/EventLike.java
  src/main/java/com/otakumap/domain/event_like/repository/EventLikeRepository.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryService.java
  src/main/java/com/otakumap/domain/event_like/service/EventLikeQueryServiceImpl.java
Labels: ✨ Feature

#67 Feat: 저장한 장소 조회 API 수정 및 저장한 루트 제목 수정
  src/main/java/com/otakumap/domain/place/entity/Place.java
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/dto/PlaceLikeResponseDTO.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeQueryServiceImpl.java
  src/main/java/com/otakumap/domain/route/entity/Route.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/domain/route_like/converter/RouteLikeConverter.java
  src/main/java/com/otakumap/domain/route_like/dto/UpdateNameRequestDTO.java
  src/main/java/com/otakumap/domain/route_like/entity/RouteLike.java
  src/main/java/com/otakumap/domain/route_like/repository/RouteLikeRepository.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandService.java
  src/main/java/com/otakumap/domain/route_like/service/RouteLikeCommandServiceImpl.java
Labels: ✨ Feature

#91 Feat: DTO에 적용한 validation을 제대로 적용시키기 위한 @Valid 추가
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
Labels: ✨ Feature

#93 Feat: 이미지 업로드 및 프로필이미지 업로드 API 구현
  build.gradle
  src/main/java/com/otakumap/domain/image/contoller/ImageController.java
  src/main/java/com/otakumap/domain/image/converter/ImageConverter.java
  src/main/java/com/otakumap/domain/image/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/otakumap/domain/image/dto/ImageRequestDTO.java
  src/main/java/com/otakumap/domain/image/entity/Image.java
  src/main/java/com/otakumap/domain/image/repository/ImageRepository.java
  src/main/java/com/otakumap/domain/image/service/ImageCommandService.java
  src/main/java/com/otakumap/domain/image/service/ImageCommandServiceImpl.java
  src/main/java/com/otakumap/domain/user/contoller/UserController.java
  src/main/java/com/otakumap/domain/user/entity/User.java
  src/main/java/com/otakumap/domain/user/service/UserCommandService.java
  src/main/java/com/otakumap/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/otakumap/global/apiPayload/exception/handler/ImageHandler.java
  src/main/java/com/otakumap/global/config/AmazonConfig.java
  src/main/java/com/otakumap/global/util/AmazonS3Util.java
Labels: ✨ Feature

#90 Feat: 진행 중인 인기 이벤트 조회 API 구현
  src/main/java/com/otakumap/domain/event/controller/EventController.java
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryCustom.java
  src/main/java/com/otakumap/domain/event/repository/EventRepositoryImpl.java
  src/main/java/com/otakumap/domain/event/service/EventCustomService.java
  src/main/java/com/otakumap/domain/event/service/EventCustomServiceImpl.java
  src/main/java/com/otakumap/domain/event/service/EventQueryServiceImpl.java
Labels: ✨ Feature

#98 Refactor: 좋아요한 루트 uri 수정 및 좋아요한 명소 중복 저장 에러
  src/main/java/com/otakumap/domain/place_like/repository/PlaceLikeRepository.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandServiceImpl.java
  src/main/java/com/otakumap/domain/route_like/controller/RouteLikeController.java
  src/main/java/com/otakumap/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature, ♻️ Refactor

#96 Feat: 이벤트 한 줄 후기 작성 API 구현
  src/main/java/com/otakumap/domain/event/converter/EventConverter.java
  src/main/java/com/otakumap/domain/event/dto/EventResponseDTO.java
  src/main/java/com/otakumap/domain/event/entity/Event.java
  src/main/java/com/otakumap/domain/eventShortReview/service/EventShortReviewCommandService.java
  src/main/java/com/otakumap/domain/event_location/converter/EventLocationConverter.java
  src/main/java/com/otakumap/domain/event_location/dto/EventLocationResponseDTO.java
  src/main/java/com/otakumap/domain/event_location/entity/EventLocation.java
  src/main/java/com/otakumap/domain/event_short_review/controller/EventShortReviewController.java
  src/main/java/com/otakumap/domain/event_short_review/converter/EventShortReviewConverter.java
  src/main/java/com/otakumap/domain/event_short_review/dto/EventShortReviewRequestDTO.java
  src/main/java/com/otakumap/domain/event_short_review/dto/EventShortReviewResponseDTO.java
  src/main/java/com/otakumap/domain/event_short_review/entity/EventShortReview.java
  src/main/java/com/otakumap/domain/event_short_review/repository/EventShortReviewRepository.java
  src/main/java/com/otakumap/domain/event_short_review/service/EventShortReviewCommandService.java
  src/main/java/com/otakumap/domain/event_short_review/service/EventShortReviewCommandServiceImpl.java
Labels: ✨ Feature

#103 Feat: 저장된(좋아요한) 장소 즐겨찾기/즐겨찾기 취소
  src/main/java/com/otakumap/domain/place_like/controller/PlaceLikeController.java
  src/main/java/com/otakumap/domain/place_like/converter/PlaceLikeConverter.java
  src/main/java/com/otakumap/domain/place_like/dto/PlaceLikeRequestDTO.java
  src/main/java/com/otakumap/domain/place_like/dto/PlaceLikeResponseDTO.java
  src/main/java/com/otakumap/domain/place_like/entity/PlaceLike.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandService.java
  src/main/java/com/otakumap/domain/place_like/service/PlaceLikeCommandServiceImpl.java
Labels: ✨ Feature
